<?php

use Illuminate\Database\Seeder;

use Illuminate\Support\Facades\DB;

class PostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = app(Faker\Generator::class);

        $images = [
            'http://pevb27s43.bkt.clouddn.com/news1.png',
            'http://pevb27s43.bkt.clouddn.com/news2.png',
            'http://pevb27s43.bkt.clouddn.com/news3.png',
        ];

        DB::table('posts')->insert([
            [
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],[
                'title' => '科氏滤膜将努力成为用户工程项目的参与者与合作伙伴',
                'type' => rand(0, 2),
                'description' => '据慧聪水工业网2018年6月21日讯 就像炎热夏日里迟迟不走的高温天气，近几年，环保产业热度只增不减。国家利好政策、环境治理力度、监管执法尺度以及环境改善速度都呈现出“前所未有”的态势，随着行业发展渐趋理性、规范，环保产业市场空间值得想象。',
                'seo_title' => '这里是seo标题',
                'seo_keywords' => '这里是seo关键词',
                'seo_description' => '这里是seo描述',
                'image' => array_random($images),
                'sort' => rand(0, 10),
                'is_stick' => rand(0, 1),
                'content' => $faker->text(),
                'clicks' => rand(0, 1000),
                'created_at' => '2018-09-10 02:16:45',
                'updated_at' => '2018-09-10 02:16:45',
            ],
        ]);
    }
}
